apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: qat

resources:
  - ../../base

commonLabels:
  environment: qat

patches:
  # 2 replicas for qat
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
    target:
      kind: Deployment
      name: api
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
    target:
      kind: Deployment
      name: web

  # QAT web runs on separate NodePort so it doesn't clash with dev:30080
  - patch: |-
      - op: replace
        path: /spec/ports/0/nodePort
        value: 30081
    target:
      kind: Service
      name: web

  # Stronger password for qat
  - patch: |-
      - op: replace
        path: /stringData/POSTGRES_PASSWORD
        value: "qat-password-change-me"
    target:
      kind: Secret
      name: postgres-secret

  # Higher resource limits for qat api
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "512Mi"
    target:
      kind: Deployment
      name: api

images:
  - name: devops-assignment/api
    newTag: latest
  - name: devops-assignment/web
    newTag: latest
